apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default

---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: hello-display
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: dev.cd.taskrun.started.v1
  subscriber:
    uri: http://el-gke-provision-listener.default.svc.cluster.local:8080
      # ref:
      #   apiVersion: triggers.tekton.dev/v1alpha1
      #   kind: EventListener
      #   name: gke-provision-listener
      #   apiVersion: v1
      #   kind: Service
      #   name: el-gke-provision-listener

