apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: task-runner
rules:
  - apiGroups: [""]
    resources:
      - pods
      - deployments
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: ["container.gcp.crossplane.io"]
    resources:
      - clusters
      - nodepools
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: ["triggers.tekton.dev"]
    resources:
      - eventlistener
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: task-runner-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: task-runner

