apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cluster-git
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/salaboy/knative-serving-events-controller
