apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: test-trigger-template
spec:
  params:
    - name: eventType
      default: unknown
    - name: source
      default: unknown
    - name: id
      default: unknown
    - name: path
    - name: git-source
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: create-gke-cluster-
      spec:
        params:
          - name: path
            value: $(tt.params.path)
        #   - name: eventType
        #     value: $(tt.params.eventType)
        #   - name: source
        #     value: $(tt.params.source)
        #   - name: id
        #     value: $(tt.params.id)
        resources:
          inputs:
            - name: source
              resourceRef:
                name: $(tt.params.git-source)

        taskRef:
          name: create-gke-cluster
