apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gke-provision-listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: provisioner
      bindings:
      - ref: test-trigger-binding
      template:
        ref: test-trigger-template

