apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gke-provision-listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: provisioner
      bindings:
      - ref: provision-cluster-binding
      template:
        ref: provision-cluster-template

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: knative-installer-listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: knative-installer
      bindings:
      - ref: knative-installer-binding
      template:
        ref: knative-installer-template

